#!/bin/bash

if [[ ! -n "$REPO_LOC" ]]; then
  REPO_LOC="$HOME/.dotfiles"
fi

if [[ ! -n "$ORIGIN" ]]; then
  ORIGIN="$HOME"
fi

if [[ ! -n "$BAK_DEST" ]]; then
  BAK_DEST="$REPO_LOC"
fi

echo  "Backing up dot files to '$BAK_DEST'..."

mkdir -p "$BAK_DEST"
mkdir -p "$BAK_DEST/.config/alacritty/"
mkdir -p "$BAK_DEST/.config/i3/"
mkdir -p "$BAK_DEST/.config/polybar/"
mkdir -p "$BAK_DEST/.config/rofi/"
mkdir -p "$BAK_DEST/.config/ranger/"
mkdir -p "$BAK_DEST/.config/deadd/"
mkdir -p "$BAK_DEST/.config/neofetch/"
mkdir -p "$BAK_DEST/.local/share/nautilus/scripts/"
mkdir -p "$BAK_DEST/.scripts/"
mkdir -p "$BAK_DEST/.toys/"
mkdir -p "$BAK_DEST/Wallpapers/"

cp -r "$ORIGIN/.config/i3/"* "$BAK_DEST/.config/i3/"
cp -r "$ORIGIN/.config/alacritty/"* "$BAK_DEST/.config/alacritty/"
cp -r "$ORIGIN/.config/polybar/"* "$BAK_DEST/.config/polybar/"
cp -r "$ORIGIN/.config/rofi/"* "$BAK_DEST/.config/rofi/"
cp -r "$ORIGIN/.config/ranger/"* "$BAK_DEST/.config/ranger/"
cp -r "$ORIGIN/.config/deadd/"* "$BAK_DEST/.config/deadd/"
cp -r "$ORIGIN/.config/neofetch/"* "$BAK_DEST/.config/neofetch/"
cp -r "$ORIGIN/.local/share/nautilus/scripts/"* "$BAK_DEST/.local/share/nautilus/scripts"
cp -r "$ORIGIN/.scripts/"* "$BAK_DEST/.scripts/"
cp -r "$ORIGIN/.toys/"* "$BAK_DEST/.toys/"

while read wp; do
  cp "$ORIGIN/Wallpapers/$wp" "$BAK_DEST/Wallpapers/"
done < "$REPO_LOC/dotfile-utils/wallpapers-to-bak"

cp "$ORIGIN/.config/compton.conf" "$BAK_DEST/.config/"
cp "$ORIGIN/.vimrc" "$BAK_DEST/"
cp "$ORIGIN/.zprofile" "$BAK_DEST/"
cp "$ORIGIN/.zshrc" "$BAK_DEST/"
cp "$ORIGIN/.Xresources" "$BAK_DEST/"

echo "Done!"
