#!/bin/bash 

if [[ ! -n "$REPO_LOC" ]]; then
  REPO_LOC="$HOME/.dotfiles"
fi

if [[ ! -n "$ORIGIN" ]]; then
  ORIGIN="$HOME"
fi

if [[ ! -n "$BAK_DEST" ]]; then
  BAK_DEST="$REPO_LOC"
fi

backup_dir() {
  local SUBDIR="$1"
  mkdir -p "$BAK_DEST/$SUBDIR/"
  cp -r "$ORIGIN/$SUBDIR/"* "$BAK_DEST/$SUBDIR/"
}

backup_file() {
  local FILE="$1"
  cp "$ORIGIN/$FILE" "$BAK_DEST/$FILE"
}

backup_wallpapers() {
  mkdir -p "$BAK_DEST/Wallpapers"
  while read wp; do
    cp "$ORIGIN/Wallpapers/$wp" "$BAK_DEST/Wallpapers/"
  done < "$REPO_LOC/dotfile-utils/wallpapers-to-bak"
}

echo  "Backing up dot files to '$BAK_DEST'..."

mkdir -p "$BAK_DEST"

backup_dir ".config/alacritty"
backup_dir ".config/i3"
backup_dir ".config/polybar"
backup_dir ".config/rofi"
backup_dir ".config/ranger"
backup_dir ".config/deadd"
backup_dir ".config/bspwm"
backup_dir ".config/sxhkd"
backup_dir ".config/neofetch"
backup_dir ".local/share/nautilus/scripts"
backup_dir ".scripts"
backup_dir ".toys"

backup_wallpapers

backup_file ".config/picom.conf"
backup_file ".vimrc"
backup_file ".zprofile"
backup_file ".zshrc"
backup_file ".Xresources"

echo "Done!"
