#!/bin/bash

# Assumes:
#- repo is stored at ~/.dotfiles
#- Using an Arch-based distro
#- yay is installed

# Useful vars
SCRIPTS_DIR="$HOME/.dotfiles/dotfile-utils"
AUR_INSTALL_CMD='yay -S'
OHMYZSH_DIR="$HOME/.oh-my-zsh" # oh-my-zsh install dir
if [[ ! -n "$INSTALL_YAY" ]] ; then
  INSTALL_YAY=1
fi

if [[ ! -n "$INSTALL_PKGS" ]] ; then
  INSTALL_PKGS=1
fi

if [[ "$INSTALL_PKGS" == "1" ]] ; then
  # Pre-install pkgs
  echo "Pacman: Updating mirrors..."
  sudo pacman -Syy

  if [[ "$INSTALL_YAY" == "1" ]] ; then 
    #   Install yay
    echo "Installing yay..."
    sudo pacman -S base-devel
    mkdir -p "$HOME/.cache/dotfiles"
    git clone https://aur.archlinux.org/yay.git "$HOME/.cache/dotfiles/yay"
    cd "$HOME/.cache/dotfiles/yay"
    makepkg -sic
    chmod -R 755 "$HOME/.cache/dotfiles"
    cd && rm -r "$HOME/.cache/dotfiles"
  fi

  # Install pkgs
  echo "Installing packages..."
  $AUR_INSTALL_CMD $(cat "$SCRIPTS_DIR/../pkgs/aur-pkg-list")
  sudo pacman -S $(cat "$SCRIPTS_DIR/../pkgs/com-pkg-list")
fi

echo "Updating dotfiles..."
$SCRIPTS_DIR/restdots

#   oh-my-zsh
echo "Installing oh-my-zsh..."
if [[ ! -e "$OHMYZSH_DIR" ]] ; then
  git clone https://github.com/ohmyzsh/ohmyzsh.git "$OHMYZSH_DIR"
else
  echo "oh-my-zsh directory already exists at $OHMYZSH_DIR. Aborting."
fi
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$OHMYZSH_DIR/custom}/plugins/zsh-autosuggestions
chmod -R 755 "$OHMYZSH_DIR"

#   Finish setup
echo "Finalizing setup..."
$SCRIPTS_DIR/extsetup

# Post-install
echo 'Done!'
