#!/bin/bash

# Assumes:
#- Using an Arch-based distro

if [[ ! -n "$DOTFILES_DIR" ]] ; then
  DOTFILES_DIR="$HOME/.dotfiles"
fi

if [[ ! -n "$INSTALL_PKGS" ]] ; then
  INSTALL_PKGS=1
fi

if [[ "$INSTALL_PKGS" == "1" ]] ; then
  $SCRIPTS_DIR/archpkgs
fi

echo "Updating dotfiles..."
$SCRIPTS_DIR/restdots

echo "Setting up zsh config..."
$SCRIPTS_DIR/zshstuff

#   Finish setup
echo "Finalizing setup..."
$SCRIPTS_DIR/extsetup

# Post-install
echo 'Done!'
