#!/bin/bash

if [[ ! -n "$REPO_LOC" ]]; then
  REPO_LOC="$HOME/.dotfiles"
fi

if [[ ! -n "$COMMIT_MSG" ]]; then
  COMMIT_MSG="$@"
fi

cd "$REPO_LOC" && git add "$REPO_LOC" && git commit -m "$COMMIT_MSG" && git push origin master
