#!/bin/bash

echo "Restoring dot files..."

if [[ ! -n "$ORIGIN" ]]; then
  ORIGIN="$HOME/.dotfiles"
fi

if [[ ! -n "$REPO_LOC" ]]; then
  REPO_LOC="$HOME/.dotfiles"
fi

if [[ ! -n "$BAK_DEST" ]]; then
  BAK_DEST="$HOME/.dotfiles/restbak"
fi

UTILS="$REPO_LOC/dotfile-utils"

mkdir -p "$BAK_DEST"
BAK_DEST="$BAK_DEST" ORIGIN="$HOME" REPO_LOC="$REPO_LOC" $UTILS/backdots # Backup current dot files

BAK_DEST="$HOME" ORIGIN="$ORIGIN" REPO_LOC="$REPO_LOC" $UTILS/backdots # Restore current dotfiles by backing them up to home.

echo "Done Restoring!"
