#PATH=$PATH:/snap/bin #snap
alias python=python3 #python -> python3
#PATH=$PATH:"/sto/.cli/linux" # termatt
#MASCRIPTS="/sto/.cli/linux/scripts"
#alias matt=termatt
#alias ma=termatt
PATH="$PATH:$HOME/.scripts:$HOME/.dotnet/tools"
TERMATT=termatt
#alias l1='ls -1'
#alias l1g='ls -1 | grep'
#alias l1eg='ls -1 | egrep'
alias kanna='ta kanna'
alias nue='ta nue'
alias osu='osu-wine'
alias mysqld='mysqld --datadir /sto/db/mysql'
alias mysql='mysql -u root -p'
