#!/bin/zsh

if [[ -e "$HOME/.scripts/env/env.zshrc" ]]; then
  source "$HOME/.scripts/env/env.zshrc"
fi

if [[ -n "$TERMATT" ]]; then
  THLN_CKB_PIPE="/tmp/ckbpipe001"
  steam "steam://run/851100"
fi

