#!/bin/bash 

SCRIPTS_DIR="$HOME/.scripts"
I3_SCRIPTS_DIR="$HOME/.scripts"
SCRIPTS_CACHE_DIR="$SCRIPTS_DIR/cache"

CURR_WP_DIR="$SCRIPTS_CACHE_DIR/wp"
TMP_WP_DIR="$SCRIPTS_CACHE_DIR/wp-tmp"
ALT_WP_DIR="$SCRIPTS_CACHE_DIR/wp-alt"
USE_WP_CONF="$I3_SCRIPTS_DIR/usewpconf"

# make directories if they don't exist
mkdir -p "$CURR_WP_DIR"
mkdir -p "$ALT_WP_DIR"

# temp name current dir
mv "$CURR_WP_DIR" "$TMP_WP_DIR"

# make alt dir current dir
mv "$ALT_WP_DIR" "$CURR_WP_DIR"

# make temp named old dir as alt dir
mv "$TMP_WP_DIR" "$ALT_WP_DIR"

# We need to delete cached colorschemes because wal will resort to the cached
# colorscheme of the "curr" wallpaper. This is undesirable because the "curr"
# wallpaper is no longer the same as it was when wal cached the "curr"
# colorscheme initially.
wal -c

# use curr-wp from what WAS the alt-dir
$USE_WP_CONF curr

# Done!
