#!/bin/zsh

if [[ -e "$HOME/.scripts/env/env.zshrc" ]]; then
  source "$HOME/.scripts/env/env.zshrc"
fi

if [[ -n "$TERMATT" ]]; then
  $TERMATT osu-wine-rpc &

  # i3 Primary 
  #   Pens
  #     With xppen official beta drivers
  #PEN='XPPEN Tablet Pen (0)'
  #     With native kernel support
  PEN='XP-PEN STAR G640 Pen Pen (0)'
  #   Active area configs
  #     With xppen official beta drivers
  #xinput set-prop "$PEN" --type=float "Coordinate Transformation Matrix" 2.7 0 -0.85 0 2.7 0 0 0 1 # Monitor layout makes this really weird for some reason...
  #     With native kernel support
  #xinput set-prop "$PEN" --type=float "Coordinate Transformation Matrix" 2.7 0 1 0 5.4 0 0 0 2 # Monitor layout makes this really weird for some reason...
  xinput set-prop "$PEN" --type=float "Coordinate Transformation Matrix" 3.2 0 1 0 6.4 0 0 0 3
  # Monitor layout makes this really weird for some reason...
fi
