#!/bin/bash

source "$HOME/.scripts/wal-functions"


WP_CONF=$1
WALLP=$(echo "$2" | sed 's/^\s*//g' | sed 's/\s*$//g')

CACHE_DIR="$HOME/.scripts/cache/wp"
CACHE_FILE_NAME="setwp-$WP_CONF"
CACHE_FILE_PATH="$CACHE_DIR/$CACHE_FILE_NAME"
USEWPCONF="$HOME/.scripts/usewpconf"

mkdir -p "$CACHE_DIR"

if [[ -L "$CACHE_FILE_PATH" || -e "$CACHE_FILE_PATH" ]] ; then
  clear_wal_cache
  rm "$CACHE_FILE_PATH"
fi

echo "$CACHE_FILE_PATH"

ln -s "$WALLP" "$CACHE_FILE_PATH"

$USEWPCONF "$WP_CONF"
