#!/bin/bash

WP_CONF=$1
WP_CACHE_FILE="$HOME/.scripts/cache/setwp-$WP_CONF"
CURR_WP_FILE="$HOME/.scripts/cache/setwp-curr"
WP_HOOK_SCRIPT="$HOME/.scripts/env/usewpconf/hook-$WP_CONF"

if [[ -e "$WP_CACHE_FILE" ]]; then
  WALLP="$(cat $WP_CACHE_FILE)"
  rm "$CURR_WP_FILE"
  ln -s "$WP_CACHE_FILE" "$CURR_WP_FILE"
  feh --bg-fill $WALLP &
fi

# Hooks for things you may want to do after setting a specific wallpaper.
# Maybe change keyboard lighting?

#   Global hook
NEW_WP=$(cat "$CURR_WP_FILE")
wal -i "$NEW_WP" &

#   Per-wallpaper hooks
if [[ -e "$WP_HOOK_SCRIPT" ]]; then
  $WP_HOOK_SCRIPT &
fi
