#!/bin/bash

ONE_DISP_IMG="$1"
DUAL_DISP_IMG="$2"

DISP_LIST_LINECOUNT=$(xrandr --listactivemonitors | wc -l)
NUM_DISPS=$(($DISP_LIST_LINECOUNT - 1))

echo $NUM_DISPS

if [[ $NUM_DISPS == 2 ]]; then
  betterlockscreen -u $DUAL_DISP_IMG
elif [[ $NUM_DISPS == 1 ]]; then
  betterlockscreen -u $ONE_DISP_IMG
fi
