#!/bin/zsh

source "$HOME/.scripts/wm/termatt"

if [[ -n "$TERMATT" ]]; then
  WM_SCRIPTS="$HOME/.scripts/wm"

  ACTIVE_AREA_SCRIPT="$WM_SCRIPTS/tab-aa"
  PEN_FOUND=$($ACTIVE_AREA_SCRIPT; echo $?)
  while [ $PEN_FOUND -gt 0 ]; do
    sleep 1
    PEN_FOUND=$($ACTIVE_AREA_SCRIPT; echo $?)
  done

  xsetwacom --set "Wacom Intuos S Pen stylus" Button 2 key "shift"
  xsetwacom --set "Wacom Intuos S Pen stylus" Button 3 key "shift"


  KILL_PICOM_SCRIPT="$WM_SCRIPTS/picom-kill"
  $KILL_PICOM_SCRIPT

  osu-wine

  START_PICOM_SCRIPT="$WM_SCRIPTS/picom"
  $START_PICOM_SCRIPT

  #ckb-next --profile 'Doremy' --mode 'Doremy'
fi

