#!/bin/bash

# use 'compton' for tryone-compton. Use 'picom' for vanilla picom (renamed from compton).
COMPOSITOR="picom"

# Disabled, because picom is broken constantly
#$COMPOSITOR #--experimental-backends
