#!/bin/bash

source "$HOME/.scripts/wm/termatt"

if [[ -n "$TERMATT" ]]; then
  # Displays
  PRIM_DISP=$(xrandr --listmonitors | grep '+\*' | cut -d ' ' -f 6 | tr -d '[:space:]')
  SEC_DISP=$(xrandr --listmonitors | grep -v '+\*' | cut -d ' ' -f 6 | cut -d ' ' -f 1 | tr -d '[:space:]')
  xrandr --output $SEC_DISP --off
  $HOME/.config/polybar/launch.sh
fi
