#!/bin/bash

DEFAULTWP="$1" # Default wallpaper if it hasn't been set before
CURR_WP="$HOME/.scripts/cache/wp/setwp-curr"

if [[ -e "$CURR_WP" ]]; then
  echo yes
  $HOME/.scripts/usewpconf curr
else
  $HOME/.scripts/setwp default "$DEFAULTWP"
fi
