#!/bin/zsh

source "$HOME/.scripts/wm/termatt"

if [[ -n "$TERMATT" ]]; then
  # i3 Primary 
  #   Pens
  #     With xppen official beta drivers
  #PEN='XPPEN Tablet Pen (0)'
  #     With native kernel support
  #PEN='XP-PEN STAR G640 Pen Pen (0)'
  # Wacom CTL-480
  PEN="Wacom Intuos S Pen"
  #   Active area configs
  #     With xppen official beta drivers
  #xinput set-prop "$PEN" --type=float "Coordinate Transformation Matrix" 2.7 0 -0.85 0 2.7 0 0 0 1 # Monitor layout makes this really weird for some reason...
  #     With native kernel support
  #xinput set-prop "$PEN" --type=float "Coordinate Transformation Matrix" 2.7 0 1 0 5.4 0 0 0 2 # Monitor layout makes this really weird for some reason...
  #xinput set-prop "$PEN" --type=float "Coordinate Transformation Matrix" 3.2 0 1 0 6.4 0 0 0 3
  # Experimental active area: 
  #   XP-Pen G640
  #XINPUT_EXIT_CODE=$(xinput set-prop "$pen" --type=float "coordinate transformation matrix" 2.7 0 1 0 5.4 0 0 0 2; echo $?)
  #   Wacom CTL-480 - Top right of tablet
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 4938x2740+1920+0; echo $?)
  #   Wacom CTL-480 - HORIZ Centered
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 4938x2740+411+0; echo $?)
  #   Wacom CTL-480 - Experimental Aspect Ratio
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 5138x2740+1920+0; echo $?)
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 6138x2740+1920+0; echo $?)
 
  # Stylus names - These change randomly for some stupid reason
  #STYLUS_NAME='Wacom Intuos S Pen stylus'
  #STYLUS_NAME='Wacom Intuos S Pen Pen (0)'

  ###MAIN###
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 5934x3165+1920+0; echo $?)
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 5340x3004+1920+0; echo $?)
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 5760x3240+1920+0; echo $?)
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 3840x2160+1920+0; echo $?)
  #(1920 * 1.9)x(1080 * 1.9 * 0.912162162162 (for adjusting to true aspect ratio. tablet is not 16:9)) ; 16:9
  #Before adjustment:
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 3648x2052+1440+0; echo $?)
  ###TOO_BIG###XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 3648x2052+1840-300; echo $?)
  ###SLIGHTLY_TOO_BIG###XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 3840x2160+1440+0; echo $?)
  #
  #
  #
  #
  #
  #
  #
  #
  XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 4032x2268+1440+0; echo $?)
  #
  #
  #
  #
  #
  #
  #
  #
  #
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 3948x2052+1840-300; echo $?)
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 3360x1890+1920+0; echo $?)
  # After adjustment:
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 3648x1872+1920+0; echo $?)
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 3840x2160+1920+0; echo $?)
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 4800x2700+1920+0; echo $?)
#ONE MON
#  XINPUT_EXIT_CODE=$(xsetwacom set "$STYLUS_NAME" MapToOutput 5340x3004+0+0; echo $?)
  #tmp
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 5934x3165+0+0; echo $?)
  
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 6047x3225+1920+0; echo $?)
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 6047x3064+1920+0; echo $?)
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 6228x3322+1920+0; echo $?)
  #XINPUT_EXIT_CODE=$(xsetwacom set 'Wacom Intuos S Pen stylus' MapToOutput 1920x1080+1920+0; echo $?)
  if [ $XINPUT_EXIT_CODE -gt 0 ]; then
    exit 1
  fi
  # Monitor layout makes this really weird for some reason...
fi
