#!/bin/bash 

SCRIPTS_DIR="$HOME/.scripts"
WM_SCRIPTS_DIR="$HOME/.scripts/wm"
SCRIPTS_CACHE_DIR="$SCRIPTS_DIR/cache"

source "$SCRIPTS_DIR/wal-functions"

CURR_WP_DIR="$SCRIPTS_CACHE_DIR/wp"
TMP_WP_DIR="$SCRIPTS_CACHE_DIR/wp-tmp"
ALT_WP_DIR="$SCRIPTS_CACHE_DIR/wp-alt"
USE_WP_CONF="$WM_SCRIPTS_DIR/usewpconf"

# make directories if they don't exist
mkdir -p "$CURR_WP_DIR"
mkdir -p "$ALT_WP_DIR"

# temp name current dir
mv "$CURR_WP_DIR" "$TMP_WP_DIR"

# make alt dir current dir
mv "$ALT_WP_DIR" "$CURR_WP_DIR"

# make temp named old dir as alt dir
mv "$TMP_WP_DIR" "$ALT_WP_DIR"


# We need to do this because we are rotating out the other wallpaper set.
# pywal may think that it doesn't need to regenerate the color sceme.
clear_wal_cache


# use curr-wp from what WAS the alt-dir
$USE_WP_CONF curr

# Done!
